before_install:
  - sudo apt-get update -y && sudo apt-get install wget

env:
  global:
  - secure: "G4frRAyffxbiSCyQ21Fo2R5o2xWlQjGO4GzudOx76apIQgA5ELmQpfaKyUBwfrdIFozFONLKPyBnEW1dySaQqAoIcspLYPGqZFjNGpNHY0qu5JV9GAgjhm7azeO5XSxvZPAYGoCXfvP87UdnumeVCdaWfRiZBTqPUHuxcAO5up8="

install:
  - wget https://github.com/spf13/hugo/releases/download/v0.12/hugo_0.12_linux_386.tar.gz
  - tar -zxvf hugo_0.12_linux_386.tar.gz hugo_0.12_linux_386/hugo_0.12_linux_386 --strip-components 1
  - chmod +x ./hugo_0.12_linux_386
  
script:
  - ./hugo_0.12_linux_386
  - ls output
