sudo: false

env:
  global:
  - secure: "G4frRAyffxbiSCyQ21Fo2R5o2xWlQjGO4GzudOx76apIQgA5ELmQpfaKyUBwfrdIFozFONLKPyBnEW1dySaQqAoIcspLYPGqZFjNGpNHY0qu5JV9GAgjhm7azeO5XSxvZPAYGoCXfvP87UdnumeVCdaWfRiZBTqPUHuxcAO5up8="

install:
  - wget https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_linux_386.tar.gz
  - tar -zxvf hugo_0.14_linux_386.tar.gz hugo_0.14_linux_386/hugo_0.14_linux_386 --strip-components 1
  - mv ./hugo_0.14_linux_386 ./hugo
  - chmod +x ./hugo
  
script:
  - ./deploy.sh
