language: go

before_install:
  - sudo apt-get update -y && sudo apt-get install curl git

install:
  - curl https://github.com/spf13/hugo/releases/download/v0.12/hugo_0.12_linux_386.tar.gz
  - extract
  - chmod +x ./hugo_0.12_linux_386
  
script:
  - cd raph.es
  - ./hugo_0.12_linux_386
