copyright  = "Raphael Estrada 2011-2015"
contentdir = "content"
layoutdir  = "layouts"
publishdir = "output"
baseurl    = "http://raph.es"
title      = "raph haXx"

[params]
  progbar  = [ "low", "low", "low", "mid", "mid", "mid", "mid", "mid", "mid", "high", "high", "high", "high", "high", "high", "high", "high", "high", "high", "done" ]

[taxonomies]
  tag      = "tags"
  project  = "projects"
  series   = "series"

[permalinks]
  blog     = "/blog/:year/:month/:slug/"
  projects = "/project/:title/"

[[menu.main]]
  name     = "root"
  url      = "/"
  weight   = 0

[[menu.main]]
  name     = "blog"
  url      = "/blog"
  weight   = 1

[[menu.main]]
  name     = "projects"
  url      = "/project"
  weight   = 2

[[menu.main]]
  name     = "about"
  url      = "/about"
  weight   = 3


