copyright  = "Raphael Estrada 2011-2014"
contentdir = "content"
layoutdir  = "layouts"
publishdir = "output"
baseurl    = "http://www.galaktor.net"
title      = "raph haXx"

[taxonomies]
  tag      = "tags"
  project  = "projects"
  series   = "series"

[permalinks]
  blog     = "/blog/:year/:month/:filename/"
  projects = "/projects/:year/:month/:filename/"

[[menu.main]]
  name     = "root"
  url      = "/"
  weight   = 0

[[menu.main]]
  name     = "blog"
  url      = "/blog"
  weight   = 1

[[menu.main]]
  name     = "projects"
  url      = "/projects"
  weight   = 2

[[menu.main]]
  name     = "about"
  url      = "/about"
  weight   = 3


